import {Container,Graphics,Text,TextStyle,Rectangle,Sprite} from 'pixi.js';import {THEME,FONT,RARITY} from './theme.js';
export const txt=(value,size=14,color=THEME.cream,weight='800')=>new Text({text:String(value),style:new TextStyle({fontFamily:FONT,fontSize:size,fontWeight:weight,fill:color,stroke:{color:THEME.ink,width:Math.max(0,size*.09)},dropShadow:{color:THEME.shadow,alpha:.25,blur:3,distance:2},align:'center',resolution:Math.min(devicePixelRatio||1,2)})});
export function gummy(w,h,top=THEME.orange,bottom=THEME.orangeDeep,radius=18){const c=new Container();const sh=new Graphics().roundRect(-w/2+3,-h/2+7,w,h,radius).fill({color:THEME.shadow,alpha:.34});c.addChild(sh);const g=new Graphics().roundRect(-w/2,-h/2,w,h,radius).fill({color:bottom}).roundRect(-w/2,-h/2,w,h-5,radius).fill({color:top}).roundRect(-w/2+5,-h/2+5,w-10,Math.max(3,h*.2),radius/2).fill({color:THEME.white,alpha:.2});c.addChild(g);return c;}
export function panel(w,h,fill=THEME.paper,radius=18,stroke=THEME.ink){const g=new Graphics().roundRect(-w/2,-h/2,w,h,radius).fill({color:fill,alpha:1});if(stroke!==null)g.roundRect(-w/2,-h/2,w,h,radius).stroke({color:stroke,width:2,alpha:.55});return g;}
export function shadowPanel(w,h,fill=THEME.paper,radius=18){const c=new Container();const sh=new Graphics().roundRect(-w/2+4,-h/2+8,w,h,radius).fill({color:THEME.shadow,alpha:.25});c.addChild(sh);c.addChild(panel(w,h,fill,radius,THEME.ink));return c;}
export function button(label,w,h,onClick,{top=THEME.orange,bottom=THEME.orangeDeep,text=THEME.cream,radius=18,size=14}= {}){const c=gummy(w,h,top,bottom,radius);c.eventMode='static';c.cursor='pointer';const t=txt(label,size,text,'900');t.anchor.set(.5);c.addChild(t);c.hitArea=new Rectangle(-w/2,-h/2,w,h);c.on('pointerover',()=>c.scale.set(1.035));c.on('pointerout',()=>c.scale.set(1));c.on('pointerdown',()=>c.scale.set(.96,.94));c.on('pointerup',()=>{c.scale.set(1.035);onClick?.()});c.on('pointerupoutside',()=>c.scale.set(1));return c;}
export function badge(label,fill=THEME.orange,text=THEME.cream){const c=new Container();const b=gummy(Math.max(48,label.length*8+22),28,fill,fill);b.scale.y=.9;c.addChild(b);const t=txt(label,10,text,'900');t.anchor.set(.5);c.addChild(t);return c;}
export function iconButton(icon,label,w=92,h=62,onClick=()=>{},top=THEME.teal){const c=button(`${icon}\n${label}`,w,h,onClick,{top,bottom:top,text:THEME.cream,size:10,radius:16});return c;}
export function progress(w,h,ratio,color=THEME.orange){const g=new Graphics().roundRect(-w/2,-h/2,w,h,h/2).fill({color:THEME.ink,alpha:.22}).roundRect(-w/2,-h/2,w*Math.max(0,Math.min(1,ratio)),h,h/2).fill({color});return g;}
export function itemCard({title,rarity='common',quantity='',texture,onClick}){const c=new Container();c.eventMode='static';c.cursor='pointer';const r=RARITY[rarity]??RARITY.common;c.addChild(shadowPanel(118,142,THEME.cream,18));const slot=panel(78,78,0xf4dfc6,15,r);slot.position.set(0,-18);c.addChild(slot);if(texture){const s=new Sprite(texture);s.anchor.set(.5);s.position.set(0,-18);s.width=68;s.height=68;slot.addChild(s)}const t=txt(title,11,THEME.ink,'900');t.anchor.set(.5);t.position.set(0,40);c.addChild(t);if(quantity){const q=badge(`×${quantity}`,THEME.orange);q.position.set(36,-54);c.addChild(q)}c.on('pointerover',()=>c.scale.set(1.04));c.on('pointerout',()=>c.scale.set(1));c.on('pointertap',()=>onClick?.());return c;}
