import {Container,Graphics,BlurFilter} from 'pixi.js';import {THEME,scaleFor} from './theme.js';import {txt,panel,shadowPanel,button,progress,badge,itemCard} from './components.js';import {state} from './state.js';
export class Screens{constructor(app,data,itemFrame=null){this.app=app;this.data=data;this.itemFrame=itemFrame;this.layer=new Container();this.overlay=new Container();this.root=new Container();this.root.addChild(this.layer,this.overlay);this.app.stage.addChild(this.root);this.dim=new Graphics();this.dim.eventMode='static';this.dim.visible=false;this.dim.on('pointertap',()=>this.close());this.overlay.addChild(this.dim);this.window=new Container();this.window.visible=false;this.overlay.addChild(this.window)}
clear(){this.layer.removeChildren()}
show(name){state.screen=name;this.close();this.clear();if(name==='home')this.home();else if(name==='inventory')this.inventory();else if(name==='shop')this.shop();else if(name==='rank')this.rank();else if(name==='chat')this.chat();else if(name==='profile')this.profile();else if(name==='settings')this.settings();else if(name==='tasks')this.tasks();else if(name==='gifts')this.gifts();else if(name==='pass')this.pass();else if(name==='mail')this.mail();else this.home();this.layout()}
header(title,sub=''){const c=new Container();const h=txt(title,20,THEME.ink,'900');h.anchor.set(.5,0);h.position.set(0,0);c.addChild(h);if(sub){const s=txt(sub,10,THEME.muted,'700');s.anchor.set(.5,0);s.position.set(0,31);c.addChild(s)}return c}
home(){const c=new Container();this.layer.addChild(c);const card=shadowPanel(390,320,THEME.cream,30);card.position.set(0,18);c.addChild(card);const ant=panel(104,104,THEME.orange,32,THEME.orangeLight);ant.position.set(0,-88);c.addChild(ant);const a=txt('🐜',52,THEME.cream,'900');a.anchor.set(.5);ant.addChild(a);const brand=txt('ANTWAR',30,THEME.orangeDeep,'900');brand.anchor.set(.5);brand.position.set(0,-17);c.addChild(brand);const sub=txt('BATTLE COLONY',10,THEME.muted,'900');sub.anchor.set(.5);sub.position.set(0,12);c.addChild(sub);const play=button('▶  PLAY',248,60,()=>this.show('battle'),{fill:THEME.orange,text:THEME.cream,stroke:THEME.orangeDeep,radius:18,size:23});play.position.set(0,72);c.addChild(play);const server=button(`●  ${state.server}   18ms`,210,42,()=>this.serverMenu(),{fill:THEME.paper,text:THEME.ink,size:11,radius:13});server.position.set(0,128);c.addChild(server);const stats=new Container();stats.position.set(0,176);for(const [i,label] of ['4,820 ONLINE','342 ROOMS'].entries()){const b=badge(label,i?THEME.paper2:THEME.green,i?THEME.ink:THEME.cream);b.position.set((i-.5)*105,0);stats.addChild(b)}c.addChild(stats);const create=button('＋ CREATE ROOM',190,44,()=>this.show('battle'),{fill:THEME.paper,text:THEME.orangeDeep,stroke:THEME.orange,radius:14,size:12});create.position.set(0,238);c.addChild(create)}
serverMenu(){const opts=this.data.servers.servers||[];this.openWindow('SERVER REGION',520,380,win=>{opts.forEach((s,i)=>{const b=button(`${s.flag}  ${s.id.toUpperCase()}     ${s.ping}`,360,48,()=>{state.server=s.id==='me'?'Middle East':s.id.toUpperCase();this.close();this.show('home')},{fill:THEME.paper,text:THEME.ink,size:12});b.position.set(0,-110+i*58);win.addChild(b)})})}
inventory(){this.openWindow('INVENTORY',800,570,win=>{const title=this.header('INVENTORY','Your colony gear and resources');title.position.set(0,-235);win.addChild(title);const items=this.data.inv.bag||[];items.forEach((it,i)=>{const card=itemCard({title:`ITEM ${it.id}`,rarity:it.rarity,quantity:it.quantity,texture:this.itemFrame,onClick:()=>this.toast(`Selected item ${it.id}`)});card.position.set(-255+(i%4)*170,-55+Math.floor(i/4)*170);win.addChild(card)});const equip=button('WARDROBE',180,46,()=>this.toast('Wardrobe ready'),{fill:THEME.orange,text:THEME.cream,radius:14,size:12});equip.position.set(-100,205);win.addChild(equip);const bag=button('BAG',140,46,()=>this.toast('Bag active'),{fill:THEME.paper,text:THEME.orangeDeep,radius:14,size:12});bag.position.set(100,205);win.addChild(bag)})}
shop(){this.openWindow('SHOP',850,590,win=>{const items=this.data.shop.items||[];items.slice(0,8).forEach((it,i)=>{const b=button(`${it.amount||'ITEM'}\n${it.price||''}`,170,92,()=>this.toast(`Purchased ${it.id}`),{fill:i===1?THEME.orange:THEME.paper,text:i===1?THEME.cream:THEME.ink,radius:18,size:12});b.position.set(-280+(i%4)*187,-100+Math.floor(i/4)*128);win.addChild(b)});const c=txt('Featured offers • Orange is the primary action',12,THEME.muted,'800');c.anchor.set(.5);c.position.set(0,190);win.addChild(c)})}
rank(){this.openWindow('LEADERBOARD',760,540,win=>{const names=['Queen Guard','Thunder Scout','Sand Raider','Kite Shield','You'];names.forEach((n,i)=>{const row=shadowPanel(620,54,i===0?THEME.cream:THEME.paper,13);row.position.set(0,-150+i*64);const t=txt(`#${i+1}   ${n}`,14,THEME.ink,'900');t.anchor.set(.5);row.addChild(t);win.addChild(row)})})}
profile(){this.openWindow('PLAYER PROFILE',720,520,win=>{const hero=shadowPanel(640,120,THEME.cream,24);hero.position.set(0,-145);win.addChild(hero);const avatar=panel(82,82,THEME.orange,26,THEME.orangeDeep);avatar.position.set(-250,-145);win.addChild(avatar);const a=txt('⚔',36,THEME.cream,'900');a.anchor.set(.5);avatar.addChild(a);const n=txt('Ant Commander',21,THEME.ink,'900');n.anchor.set(0,.5);n.position.set(-190,-160);win.addChild(n);const lv=txt('LEVEL 18',11,THEME.orangeDeep,'900');lv.anchor.set(0,.5);lv.position.set(-190,-130);win.addChild(lv);const xp=progress(430,12,.62,THEME.orange);xp.position.set(0,-76);win.addChild(xp);[['POWER','14,850'],['WINS','428'],['RANK','#42']].forEach((x,i)=>{const b=shadowPanel(180,80,THEME.paper,16);b.position.set(-200+i*200,60);const a=txt(x[0],10,THEME.muted,'800');a.anchor.set(.5);a.position.set(0,-10);b.addChild(a);const v=txt(x[1],19,THEME.orangeDeep,'900');v.anchor.set(.5);v.position.set(0,14);b.addChild(v);win.addChild(b)})})}
settings(){this.openWindow('SETTINGS & CONTROLS',760,560,win=>{['GAMEPLAY','GRAPHICS','AUDIO','LANGUAGE'].forEach((x,i)=>{const b=button(x,250,48,()=>this.toast(`${x} selected`),{fill:i===0?THEME.orange:THEME.paper,text:i===0?THEME.cream:THEME.ink,radius:14,size:12});b.position.set(-180+(i%2)*360,-170+Math.floor(i/2)*66);win.addChild(b)});[['AUTO-SAVE','autoSave'],['SHOW PING','showPing'],['SCREEN FX','screenFx'],['MUSIC','music'],['SFX','sfx']].forEach((x,i)=>{const on=state.settings[x[1]];const b=button(`${x[0]}   ${on?'ON':'OFF'}`,260,44,()=>{state.settings[x[1]]=!state.settings[x[1]];this.settings()},{fill:on?THEME.orange:THEME.paper,text:on?THEME.cream:THEME.ink,radius:13,size:11});b.position.set(0,-20+i*55);win.addChild(b)})})}
chat(){this.openWindow('COLONY CHAT',780,550,win=>{state.chat.forEach((m,i)=>{const row=shadowPanel(630,64,i%2?THEME.paper:THEME.cream,14);row.position.set(0,-160+i*75);const u=txt(m.user,11,THEME.orangeDeep,'900');u.anchor.set(0,.5);u.position.set(-285,-12);row.addChild(u);const tx=txt(m.text,12,THEME.ink,'700');tx.anchor.set(0,.5);tx.position.set(-285,15);row.addChild(tx);win.addChild(row)});const send=button('SEND',120,42,()=>{state.chat.push({user:'You',text:'Ready!',time:'now'});this.chat()},{fill:THEME.orange,text:THEME.cream,radius:13,size:12});send.position.set(260,195);win.addChild(send)})}
tasks(){this.openWindow('DAILY TASKS',760,560,win=>{(this.data.nav.dailyQuests?.daily||[]).forEach((q,i)=>{const r=shadowPanel(620,72,THEME.paper,14);r.position.set(0,-165+i*82);const t=txt(`TASK ${i+1}    ${q.progress}/${q.max}`,13,THEME.ink,'900');t.anchor.set(.5);r.addChild(t);win.addChild(r)})})}
gifts(){this.openWindow('DAILY GIFTS',760,520,win=>{(this.data.nav.dailyRewards||[]).forEach((r,i)=>{const b=button(`DAY ${r.day}\n+${r.amount}`,150,96,i===0?()=>this.toast('Reward claimed!'):()=>this.toast('Locked'),{fill:i===0?THEME.orange:THEME.paper,text:i===0?THEME.cream:THEME.ink,radius:17,size:12});b.position.set(-270+(i%4)*180,-90+Math.floor(i/4)*125);win.addChild(b)})})}
pass(){this.openWindow('ROYAL PASS',780,560,win=>{const p=progress(560,18,.7,THEME.orange);p.position.set(0,-180);win.addChild(p);for(let i=0;i<6;i++){const r=button(`T-${i+1}\nREWARD`,150,92,()=>this.toast(`Tier ${i+1}`),{fill:i===2?THEME.orange:THEME.paper,text:i===2?THEME.cream:THEME.ink,radius:16,size:12});r.position.set(-280+(i%3)*280,-70+Math.floor(i/3)*125);win.addChild(r)}})}
mail(){this.openWindow('MAILBOX',720,520,win=>{['Battle reward','Welcome pack','System message'].forEach((m,i)=>{const b=shadowPanel(590,60,THEME.paper,14);b.position.set(0,-130+i*78);const t=txt(m,13,THEME.ink,'900');t.anchor.set(0,.5);t.position.set(-270,0);b.addChild(t);win.addChild(b)})})}
openWindow(title,w,h,render){this.window.removeChildren();this.dim.visible=true;this.window.visible=true;const sh=shadowPanel(w,h,THEME.paper,28);sh.position.set(this.app.screen.width/2,this.app.screen.height/2);this.window.addChild(sh);const head=txt(title,22,THEME.orangeDeep,'900');head.anchor.set(.5);head.position.set(this.app.screen.width/2,this.app.screen.height/2-h/2+34);this.window.addChild(head);const close=button('×',44,44,()=>this.close(),{fill:THEME.orange,text:THEME.cream,radius:14,size:25});close.position.set(this.app.screen.width/2+w/2-38,this.app.screen.height/2-h/2+36);this.window.addChild(close);render(this.window);this.window.filters=[new BlurFilter({strength:0,quality:1})]}
close(){this.dim.visible=false;this.window.visible=false;this.window.removeChildren()}
toast(msg){const t=new Container();const b=panel(Math.min(420,Math.max(240,msg.length*8+36)),48,THEME.orange,15,THEME.orangeDeep);t.addChild(b);const tx=txt(msg,11,THEME.cream,'900');tx.anchor.set(.5);t.addChild(tx);t.position.set(this.app.screen.width/2,this.app.screen.height-70);this.overlay.addChild(t);setTimeout(()=>t.destroy(),1500)}
layout(){const s=scaleFor(this.app.screen.width,this.app.screen.height);this.layer.scale.set(s);this.layer.position.set(this.app.screen.width/2,this.app.screen.height/2+18);this.overlay.scale.set(1);this.dim.clear().rect(0,0,this.app.screen.width,this.app.screen.height).fill({color:THEME.night,alpha:.52)}}
}
