import {Container,Graphics} from 'pixi.js';import {THEME,scaleFor} from './theme.js';import {txt,button,gummy,panel,shadowPanel,badge,iconButton,progress,itemCard} from './components.js';import {state} from './state.js';
export class Screens{
 constructor(app,data={},itemFrame=null){this.app=app;this.data=data;this.itemFrame=itemFrame;this.layer=new Container();this.overlay=new Container();this.root=new Container();this.root.addChild(this.layer,this.overlay);app.stage.addChild(this.root);this.dim=new Graphics();this.dim.eventMode='static';this.dim.on('pointertap',()=>this.close());this.overlay.addChild(this.dim);this.window=new Container();this.overlay.addChild(this.window)}
 clear(){this.layer.removeChildren()}
 show(name){state.screen=name;this.close();this.clear();({home:()=>this.home(),battle:()=>this.battle(),inventory:()=>this.inventory(),shop:()=>this.shop(),rank:()=>this.rank(),chat:()=>this.chat(),profile:()=>this.profile(),settings:()=>this.settings(),tasks:()=>this.tasks(),gifts:()=>this.gifts(),pass:()=>this.pass(),mail:()=>this.mail()}[name]||(()=>this.home()))();this.layout()}
 layout(){const w=this.app.screen.width,h=this.app.screen.height,s=scaleFor(w,h);this.layer.position.set(w/2,h/2);this.layer.scale.set(s);this.overlay.position.set(0,0);this.dim.clear().rect(0,0,w,h).fill({color:THEME.ink,alpha:.68});this.window.position.set(w/2,h/2);this.dim.visible=this.window.visible}
 close(){this.window.removeChildren();this.window.visible=false;this.dim.visible=false}
 openWindow(title,w,h,build){this.window.removeChildren();this.window.visible=true;const box=shadowPanel(w,h,THEME.cream,26);this.window.addChild(box);const head=gummy(w-18,62,THEME.purple,0x7743b0,18);head.position.set(0,-h/2+42);this.window.addChild(head);const t=txt(title,20);t.anchor.set(.5);head.addChild(t);const x=button('×',42,42,()=>this.close(),{top:THEME.rose,bottom:0xb63d60,size:22,radius:14});x.position.set(w/2-34,-h/2+42);this.window.addChild(x);build(this.window);this.layout()}
 home(){const c=new Container();this.layer.addChild(c);this.drawBackdrop();this.topBar(c);this.bannerRow(c);this.logoActions(c);this.hero(c);this.grid(c);this.playNow(c);this.bottomNav(c)}
 drawBackdrop(){const g=new Graphics();const w=this.app.screen.width,h=this.app.screen.height;g.rect(0,0,w,h).fill({color:THEME.skyTop});for(let i=0;i<8;i++){g.circle((i*193)%Math.max(w,1),h*.18+(i%4)*120,120+i*18).fill({color:THEME.skyBottom,alpha:.12})}this.layer.addChild(g);for(let i=0;i<30;i++){const p=new Graphics().star(0,0,4,Math.random()*2+1).fill({color:THEME.gold,alpha:.5});p.position.set(Math.random()*w-this.app.screen.width/2,Math.random()*h-this.app.screen.height/2);this.layer.addChild(p)}}
 topBar(c){const w=Math.min(1120,this.app.screen.width/scaleFor(this.app.screen.width,this.app.screen.height)-36);const bar=new Graphics().roundRect(-w/2,-36,w,72,24).fill({color:THEME.glass,alpha:.84}).stroke({color:THEME.gold,width:2,alpha:.5});bar.position.set(0,-360);c.addChild(bar);const av=gummy(58,58,THEME.gold,THEME.goldDeep,29);av.position.set(-w/2+38,0);bar.addChild(av);const a=txt('🐜',30);a.anchor.set(.5);av.addChild(a);const name=txt('Ant Commander',15);name.anchor.set(0,.5);name.position.set(-w/2+75,-9);bar.addChild(name);const lv=badge('LV 18',THEME.goldDeep);lv.position.set(-w/2+90,18);bar.addChild(lv);[['🪙','12,450',THEME.gold],['◆','350',THEME.sky]].forEach((x,i)=>{const pill=gummy(150,42,x[2],i?0x327bb1:THEME.goldDeep,21);pill.position.set(90+i*170,0);bar.addChild(pill);const tx=txt(`${x[0]}  ${x[1]}   +`,13,THEME.ink);tx.anchor.set(.5);pill.addChild(tx)});const set=button('⚙',46,46,()=>this.settings(),{top:THEME.cream,bottom:0xdcc9b1,text:THEME.ink,size:20,radius:23});set.position.set(w/2-32,0);bar.addChild(set)}
 bannerRow(c){[-1,1].forEach((side,i)=>{const b=button(i?'♛  QUEEN’S FAVOR':'🏆  COLONY RANK',300,54,()=>i?this.gifts():this.rank(),{top:i?THEME.purple:THEME.gold,bottom:i?0x7743b0:THEME.goldDeep,size:14,radius:18});b.position.set(side*160,-285);c.addChild(b)})}
 logoActions(c){const logo=txt('ANTWAR',62,THEME.gold,'900');logo.anchor.set(.5);logo.position.set(0,-222);c.addChild(logo);[[ -310,-220,'🎡','WHEEL',THEME.rose],[-310,-155,'📖','HOW TO',THEME.sky],[310,-220,'🎁','VIP BONUS',THEME.gold],[310,-155,'🎉','FIRST PACK',THEME.rose]].forEach(x=>{const b=iconButton(x[2],x[3],108,58,()=>this.toast(`${x[3]} opened`),x[4]);b.position.set(x[0],x[1]);c.addChild(b)})}
 hero(c){const b=gummy(790,108,THEME.orange,THEME.goldDeep,24);b.position.set(0,-62);c.addChild(b);const ant=txt('🐜 🐜 🐜',28);ant.anchor.set(.5);ant.position.set(-265,0);b.addChild(ant);const title=txt('JOIN THE SWARM',29);title.anchor.set(.5);title.position.set(0,-10);b.addChild(title);const sub=txt('16 PLAYERS  •  FIND A MATCH',12,THEME.cream,'900');sub.anchor.set(.5);sub.position.set(0,25);b.addChild(sub);const go=button('▶',62,62,()=>this.show('battle'),{top:THEME.rose,bottom:0xb63d60,size:28,radius:31});go.position.set(310,0);b.addChild(go)}
 grid(c){[['⚑','SQUAD UP',THEME.green],['⌂','PRIVATE NEST',THEME.teal],['♛','QUEEN’S TABLE',THEME.purple]].forEach((x,i)=>{const b=button(`${x[0]}\n${x[1]}`,230,126,()=>this.toast(`${x[1]} opened`),{top:x[2],bottom:0x2b1810,text:THEME.cream,size:15,radius:22});b.position.set((i-1)*250,55);c.addChild(b)})}
 playNow(c){const b=button('🐜  PLAY NOW!',300,72,()=>this.show('battle'),{top:THEME.orange,bottom:THEME.orangeDeep,size:22,radius:24});b.rotation=-.045;b.position.set(285,145);c.addChild(b)}
 bottomNav(c){const labels=[['🎨','SKINS','inventory'],['🎟','EVENTS','tasks'],['🏠','NEST','home'],['👥','COLONY','chat'],['🛒','MARKET','shop']];const w=760;const bar=panel(w,78,THEME.glass,25,null);bar.alpha=.94;bar.position.set(0,350);c.addChild(bar);labels.forEach((x,i)=>{const b=button(`${x[0]}\n${x[1]}`,122,i===2?68:58,()=>this.show(x[2]),{top:i===2?THEME.sky:THEME.cream,bottom:i===2?0x327bb1:0xd9c4a7,text:i===2?THEME.cream:THEME.ink,size:10,radius:18});b.position.set(-300+i*150,i===2?-7:0);bar.addChild(b)})}
 battle(){this.openWindow('BATTLE HUB',820,510,w=>{const t=txt('CHOOSE YOUR SWARM',24,THEME.orangeDeep);t.anchor.set(.5);t.position.set(0,-185);w.addChild(t);['JOIN THE SWARM','DESERT RAID','COLONY WAR','PRIVATE NEST'].forEach((r,i)=>{const b=button(`${r}\n${12+i*4}/20 PLAYERS`,280,70,()=>this.toast(`${r} joined`),{top:i===0?THEME.orange:THEME.teal,bottom:i===0?THEME.orangeDeep:0x168e85,size:12});b.position.set((i%2?150:-150),-90+Math.floor(i/2)*100);w.addChild(b)})})}
 serverMenu(){this.openWindow('SERVER REGION',520,380,w=>{(this.data.servers?.servers||[{id:'me',flag:'🌍',ping:'18ms'}]).slice(0,5).forEach((s,i)=>{const b=button(`${s.flag||'•'}  ${(s.id||'REGION').toUpperCase()}   ${s.ping||'--'}`,360,48,()=>{state.server=s.id==='me'?'Middle East':String(s.id).toUpperCase();this.close();this.show('home')},{top:THEME.cream,bottom:0xdcc9b1,text:THEME.ink,size:12,radius:14});b.position.set(0,-110+i*58);w.addChild(b)})})}
 inventory(){this.openWindow('INVENTORY',820,570,w=>{(this.data.inv?.bag||[]).slice(0,12).forEach((it,i)=>{const b=itemCard({title:`ITEM ${it.id||i+1}`,rarity:it.rarity,quantity:it.quantity,texture:this.itemFrame,onClick:()=>this.toast('Item selected')});b.position.set(-255+i%4*170,-75+Math.floor(i/4)*165);w.addChild(b)});})}
 shop(){this.openWindow('MARKET',850,570,w=>{(this.data.shop?.items||[]).slice(0,8).forEach((it,i)=>{const b=button(`${it.amount||'PACK'}\n${it.price||'BUY'}`,170,100,()=>this.toast('Purchase ready'),{top:i%3===0?THEME.gold:i%3===1?THEME.purple:THEME.teal,bottom:THEME.ink,size:12});b.position.set(-280+i%4*187,-75+Math.floor(i/4)*135);w.addChild(b)})})}
 rank(){this.openWindow('COLONY RANK',720,520,w=>{['Queen Guard','Thunder Scout','Sand Raider','Kite Shield','You'].forEach((n,i)=>{const r=shadowPanel(600,54,i===0?0xffedc2:THEME.cream,14);r.position.set(0,-135+i*64);const t=txt(`#${i+1}   ${n}                 ${15420-i*730}`,13,THEME.ink);t.anchor.set(.5);r.addChild(t);w.addChild(r)})})}
 profile(){this.openWindow('PLAYER PROFILE',700,500,w=>{const av=gummy(110,110,THEME.orange,THEME.orangeDeep,35);av.position.set(-230,-100);w.addChild(av);const a=txt('🐜',55);a.anchor.set(.5);av.addChild(a);const n=txt('ANT COMMANDER',25,THEME.orangeDeep);n.anchor.set(0,.5);n.position.set(-155,-125);w.addChild(n);const xp=progress(380,14,.68,THEME.orange);xp.position.set(20,-80);w.addChild(xp);[['POWER','14,850'],['WINS','428'],['RANK','#42']].forEach((s,i)=>{const b=shadowPanel(170,80,THEME.cream,16);b.position.set(-185+i*185,60);const t=txt(`${s[0]}\n${s[1]}`,13,THEME.ink);t.anchor.set(.5);b.addChild(t);w.addChild(b)})})}
 settings(){this.openWindow('SETTINGS',680,500,w=>{['AUTO-SAVE','SHOW PING','SCREEN FX','MUSIC','SFX'].forEach((n,i)=>{const key=['autoSave','showPing','screenFx','music','sfx'][i],on=!!state.settings[key];const b=button(`${n}   ${on?'ON':'OFF'}`,300,48,()=>{state.settings[key]=!on;this.settings()},{top:on?THEME.green:THEME.cream,bottom:on?0x3c8f39:0xd9c4a7,text:on?THEME.cream:THEME.ink,size:12});b.position.set(0,-145+i*58);w.addChild(b)})})}
 chat(){this.openWindow('COLONY CHAT',720,520,w=>{(state.chat||[]).slice(-5).forEach((m,i)=>{const r=shadowPanel(590,58,i%2?THEME.cream:0xffedc2,13);r.position.set(0,-140+i*66);const t=txt(`${m.user||'Player'}: ${m.text||''}`,12,THEME.ink);t.anchor.set(.5);r.addChild(t);w.addChild(r)});const s=button('SEND',120,42,()=>this.toast('Message sent'),{top:THEME.orange,size:12});s.position.set(235,180);w.addChild(s)})}
 tasks(){this.simpleList('DAILY EVENTS',['Win 3 battles','Open 2 chests','Play with a squad','Earn 500 Sap','Visit the Market'])}
 gifts(){this.simpleList('QUEEN’S FAVOR',['Daily bonus ready','VIP chest','First pack','Golden reward','Claim 250 Sap'])}
 pass(){this.simpleList('COLONY PASS',['Tier 1 • 100 Sap','Tier 2 • Crystal','Tier 3 • Queen badge','Tier 4 • Skin','Tier 5 • Golden chest'])}
 mail(){this.simpleList('MAIL',['Welcome to the colony!','Rank reward delivered','Daily reward available','Squad invitation','Maintenance notice'])}
 simpleList(title,items){this.openWindow(title,680,500,w=>{items.forEach((n,i)=>{const r=shadowPanel(540,55,THEME.cream,14);r.position.set(0,-130+i*62);const t=txt(`✦  ${n}`,12,THEME.ink);t.anchor.set(.5);r.addChild(t);w.addChild(r)})})}
 toast(message){const t=button(message,300,54,()=>this.close(),{top:THEME.ink,bottom:THEME.ink,size:13,radius:20});t.position.set(this.app.screen.width/2,this.app.screen.height-90);this.overlay.addChild(t);setTimeout(()=>t.destroy(),1700)}
}
